### ISSUE TITLE
switch from `summarise()` to `reframe()`

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/pacta.portfolio.report#14]
Error when running webtool_script_3.R in RMI_PACTA:latest:

```
Warning message:
Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.
ℹ The deprecated feature was likely used in the pacta.portfolio.report package.
```

**Comment by cjyetman** [comment]
@AlexAxthelm do you have a reproducible example that throws this warning? I'd like to take a look at it because it might be a data problem, which might suggest a problem further upstream. Given the `summarise()` command, it seems like this could only happen if the `port_weight` for any given group has more than one unique value, which shouldn't be the case.

https://github.com/RMI-PACTA/pacta.portfolio.report/blob/3c8c91e03bbea9778369d738d625fa51531ed5af/R/prep_company_bubble.R#L31-L38

**Comment by jdhoffa** [comment]
Did we end up validating the reason why we were getting two rows per grouping?

**Comment by cjyetman** [comment]
Not sure, but I don't think so.

**Comment by AlexAxthelm** [comment]
@jdhoffa Not that I know of. Might be worth flagging for an investigation spike.
